

const fs   = require('fs');
const path = require('path');

const PROJECTS_DIR  = path.join(__dirname, 'projects');
const OUTPUT_FILE   = path.join(__dirname, 'projects-data.js');
const IMAGE_EXTS    = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif']);

// helpers  fubnctions dertermine if a file is an image, read the description.txt for a project, and get all images in a project folder
function isImage(filename) {
  return IMAGE_EXTS.has(path.extname(filename).toLowerCase());
}

function readDescription(folder) {
  const txtPath = path.join(PROJECTS_DIR, folder, 'description.txt');
  if (!fs.existsSync(txtPath)) return { description: '', link: null };

  const raw   = fs.readFileSync(txtPath, 'utf-8').trim();
  const lines = raw.split('\n').map(l => l.trim()).filter(Boolean);

  let link = null;
  let descLines = lines;

  const last = lines[lines.length - 1];
  if (last && /^https?:\/\//i.test(last)) {
    link      = last;
    descLines = lines.slice(0, -1);
  }

  return { description: descLines.join(' '), link };
}

function getImages(folder) {
  const dir = path.join(PROJECTS_DIR, folder);
  return fs.readdirSync(dir)
    .filter(isImage)
    .map(f => `projects/${folder}/${f}`);
}

// main logic: read all project folders, extract data, and write output file
if (!fs.existsSync(PROJECTS_DIR)) {
  fs.mkdirSync(PROJECTS_DIR);
  console.log('Created projects/ folder — add subfolders to get started.');
}

const folders = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true })
  .filter(e => e.isDirectory())
  .map(e => e.name)
  .sort();

const projects = folders.map(folder => {
  const { description, link } = readDescription(folder);
  const images = getImages(folder);
  console.log(`  ✔  ${folder}  (${images.length} image${images.length !== 1 ? 's' : ''})`);
  return { title: folder, description, images, link };
});

// collect all images for the BG_IMAGES array (used for the homepage background)
const bgImages = projects.flatMap(p => p.images);

// write the output file with the collected data
const json    = JSON.stringify(projects, null, 2);
const bgJson  = JSON.stringify(bgImages, null, 2);

const output = `// AUTO-GENERATED by generate.js — do not edit by hand.
// Add project folders inside the projects/ directory, then re-run:
//   node generate.js
// (Render runs this automatically on every deploy as the Build Command.)

var PROJECTS = ${json};

var BG_IMAGES = ${bgJson};
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`\nWrote ${projects.length} project(s) → projects-data.js`);
