// AUTO-GENERATED by generate.js — do not edit by hand.
// Add project folders inside the projects/ directory, then re-run:
//   node generate.js
// (Render runs this automatically on every deploy as the Build Command.)

const PROJECTS = [
  {
    "title": "Robot Arm 4DOF",
    "description": "A 4 degrees-of-freedom robotic arm designed and built entirely from scratch. Structural components were 3D printed and driven by servo motors with embedded microcontroller control. Built to explore forward kinematics, joint design, and fabrication workflows.",
    "images": [
      "projects/Robot Arm 4DOF/Screenshot from 2025-08-29 23-47-23.png"
    ],
    "link": null
  },
  {
    "title": "Robot Arm 6DOF",
    "description": "An extended 6 degrees-of-freedom robotic arm building on the 4DOF design. The additional joints significantly increase workspace and dexterity, enabling more complex manipulation tasks. Features redesigned joint geometry for improved range of motion and structural rigidity.",
    "images": [
      "projects/Robot Arm 6DOF/Screenshot from 2025-08-29 23-48-31.png"
    ],
    "link": null
  }
];

const BG_IMAGES = [
  "projects/Robot Arm 4DOF/Screenshot from 2025-08-29 23-47-23.png",
  "projects/Robot Arm 6DOF/Screenshot from 2025-08-29 23-48-31.png"
];
