// AUTO-GENERATED by generate.js — do not edit by hand.
// Add project folders inside the projects/ directory, then re-run:
//   node generate.js
// (Render runs this automatically on every deploy as the Build Command.)

const PROJECTS = [
  {
    "title": "3D Printed Drone",
    "description": "**Custom 3D-Printed Drone** An ongoing personal project focused on designing and 3D printing a fully custom drone from scratch. The frame, body shell, arms, and motor mounts are all original CAD designs made with printability, strength, and weight reduction in mind. The drone is being printed with carbon fiber reinforced PETG because of its stiffness, durability, and vibration resistance, which are important for a stable flight platform. The project is currently in the design and prototyping phase, with work focused on refining the frame geometry, improving motor mount strength, and preparing the design for flight testing.",
    "images": [],
    "link": null
  },
  {
    "title": "Autonomous Desktop CNC Machine",
    "description": "**Autonomous Desktop CNC Machine — WPI Major Qualifying Project** For my WPI Major Qualifying Project, I worked with a team of six engineers to continue the development of a low-cost, open-source autonomous desktop CNC machine for student manufacturing education. The machine was designed to mill wood, plastics, and non-ferrous metals across four axes. Our team improved several major systems on the machine, including the automatic tool changer, dust collection system, coolant system, rotary 4th axis, and CAM workflow. The project included a reverse-engineered three-slot automatic tool changer with a touch-off sensor for measuring tool offsets, a redesigned dust boot with a magnetic brush attachment, and a new dust skirt with print-in-place bristles for better chip evacuation. We also overhauled the coolant system by adding a chip auger, sump, bag filter, drain pan, and improved flow capacity. The 4th-axis rotary unit was installed and configured, allowing the machine to run multi-axis toolpaths. On the software and CAM side, the team developed collision simulations, fixture models, and a feeds-and-speeds library to make the machine easier and safer to use. My main Fusion 360 contributions were the custom coolant drain bed and the ECU enclosure. The drain bed was designed as a sloped center-draining tray to guide chips and coolant into the sump. I also modeled the full ECU enclosure, including the controller board, power supply, terminal blocks, and internal wiring layout, so the electronics could be mounted cleanly and safely inside the machine.",
    "images": [],
    "link": null
  },
  {
    "title": "Checkers Online",
    "description": "Checkers Online Checkers Online is a browser-based checkers game I built independently for a web development course. The game supports both local two-player play and online multiplayer through account login. I implemented the full checkers rule set, including legal moves, captures, kinging, turn handling, and game resets. The site also includes a light/dark theme toggle, sound effects, and visual feedback for moves and captures. For online play, I connected the frontend to a backend server that handles user authentication and multiplayer matchmaking. I built the project end-to-end, including the game logic, UI design, audio, visual effects, and server integration.",
    "images": [
      "projects/Checkers Online/gameplay.png",
      "projects/Checkers Online/login-screen.png"
    ],
    "link": "https://a4-nicholasdriscoll.onrender.com/"
  },
  {
    "title": "ROS2 SLAM Autonomous Explorer",
    "description": "Autonomous LiDAR-Based Mapping and Exploration Robot Originally developed as an RBE 3002 Team 14 robotics project, this system was first implemented on a TurtleBot platform using ROS2. I am now modifying and adapting the project for a different physical mobile robot, including integrating a new LiDAR sensor and tuning the software stack for the new hardware. The project focuses on autonomous exploration of an unknown environment. The robot starts without a complete map and uses LiDAR data to detect frontiers, which are the boundaries between explored free space and unknown areas. An A* path planner then generates a route to the closest useful frontier, while the robot follows the path and SLAM Toolbox updates the occupancy grid in real time. This process repeats until the space is mapped. The system uses ROS2 topics for LiDAR scans, odometry, mapping, path planning, and velocity control. RViz2 is used to visualize the map, inflated obstacle space, frontier targets, planned path, robot pose, and localization data. A later phase added kidnapping recovery using AMCL, where the robot can recover its position after being moved by reinitializing the particle filter and converging back on its true pose. My current work is focused on moving the system from the original TurtleBot setup to a different robot platform, adjusting the LiDAR integration, odometry handling, navigation behavior, and tuning needed for real-world sensor noise and drift.",
    "images": [],
    "link": null
  },
  {
    "title": "TinyPets",
    "description": "TinyPets TinyPets is a retro pixel-art web game created as a group project. Players can make an account, earn credits, buy randomized eggs from the in-game shop, hatch them through a click-based hatching sequence, and collect the pets they receive. Each pet is saved to the player’s collection with its own unique ID and sell value, giving players the option to sell pets for credits and continue buying and hatching more eggs. My main contribution was the backend of the website. I worked on the server-side logic, database interactions, and API routes that supported the shop, egg purchasing, hatching system, and pet collection features.",
    "images": [],
    "link": null
  },
  {
    "title": "xArm Color Ball Sorter",
    "description": "Vision-Guided Robotic Sorting System Built a vision-guided robotic sorting system over five robotics labs using an xArm robotic arm and an overhead camera. The system detects colored balls on a custom checkerboard workspace, identifies their color and position, then commands the robot to pick them up and place them into the correct color-coded bins. I designed the checkerboard, tile grid, ball holders, and camera mount in Fusion 360, then 3D printed the parts. The checkerboard also served as a calibration tool, allowing the camera to convert pixel locations into real-world coordinates that the robot could reach. The project progressed from basic arm control to forward kinematics, inverse kinematics, trajectory planning, singularity avoidance, and finally full camera-based pick-and-place automation. By the final stage, the system could sort red, orange, yellow, and green balls without manual input.",
    "images": [
      "projects/xArm Color Ball Sorter/cad-assembled.png",
      "projects/xArm Color Ball Sorter/cad-exploded.png",
      "projects/xArm Color Ball Sorter/robot-gripper.png",
      "projects/xArm Color Ball Sorter/robot-overview.png",
      "projects/xArm Color Ball Sorter/robot-picking.png"
    ],
    "link": null
  }
];

const BG_IMAGES = [
  "projects/Checkers Online/gameplay.png",
  "projects/Checkers Online/login-screen.png",
  "projects/xArm Color Ball Sorter/cad-assembled.png",
  "projects/xArm Color Ball Sorter/cad-exploded.png",
  "projects/xArm Color Ball Sorter/robot-gripper.png",
  "projects/xArm Color Ball Sorter/robot-overview.png",
  "projects/xArm Color Ball Sorter/robot-picking.png"
];
