// AUTO-GENERATED by generate.js — do not edit by hand.
// Add project folders inside the projects/ directory, then re-run:
//   node generate.js
// (Render runs this automatically on every deploy as the Build Command.)

var PROJECTS = [
  {
    "title": "3D Printed Drone",
    "description": "An ongoing personal project focused on designing and 3D printing a fully custom drone from scratch. The frame, body shell, arms, and motor mounts are all original CAD designs made with printability, strength, and weight reduction in mind. The drone is being printed with carbon fiber reinforced PETG because of its stiffness, durability, and vibration resistance, which are important for a stable flight platform. The project is currently in the design and prototyping phase, with work focused on refining the frame geometry, improving motor mount strength, and preparing the design for flight testing.",
    "images": [
      "projects/3D Printed Drone/cad-exploded.png"
    ],
    "link": null
  },
  {
    "title": "Checkers Online",
    "description": "Checkers Online Checkers Online is a browser-based checkers game I built independently for a web development course. The game supports both local two-player play and online multiplayer through account login. I implemented the full checkers rule set, including legal moves, captures, kinging, turn handling, and game resets. The site also includes a light/dark theme toggle, sound effects, and visual feedback for moves and captures. For online play, I connected the frontend to a backend server that handles user authentication and multiplayer matchmaking. I built the project end-to-end, including the game logic, UI design, audio, visual effects, and server integration.",
    "images": [
      "projects/Checkers Online/gameplay.png",
      "projects/Checkers Online/login-screen.png"
    ],
    "link": "https://a4-nicholasdriscoll.onrender.com/"
  },
  {
    "title": "ROS2 SLAM Autonomous Explorer",
    "description": "Autonomous LiDAR-Based Mapping and Exploration Robot Originally developed as an RBE 3002 Team 14 robotics project, this system was first implemented on a TurtleBot platform using ROS2. I am now modifying and adapting the project for a different physical mobile robot, including integrating a new LiDAR sensor and tuning the software stack for the new hardware. The project focuses on autonomous exploration of an unknown environment. The robot starts without a complete map and uses LiDAR data to detect frontiers, which are the boundaries between explored free space and unknown areas. An A* path planner then generates a route to the closest useful frontier, while the robot follows the path and SLAM Toolbox updates the occupancy grid in real time. This process repeats until the space is mapped. The system uses ROS2 topics for LiDAR scans, odometry, mapping, path planning, and velocity control. RViz2 is used to visualize the map, inflated obstacle space, frontier targets, planned path, robot pose, and localization data. A later phase added kidnapping recovery using AMCL, where the robot can recover its position after being moved by reinitializing the particle filter and converging back on its true pose. My current work is focused on moving the system from the original TurtleBot setup to a different robot platform, adjusting the LiDAR integration, odometry handling, navigation behavior, and tuning needed for real-world sensor noise and drift.",
    "images": [
      "projects/ROS2 SLAM Autonomous Explorer/01-robot-hardware.png",
      "projects/ROS2 SLAM Autonomous Explorer/02-robot-exploring.png",
      "projects/ROS2 SLAM Autonomous Explorer/03-rviz-map-building.png",
      "projects/ROS2 SLAM Autonomous Explorer/04-rviz-completed-map.png"
    ],
    "link": null
  },
  {
    "title": "TinyPets",
    "description": "TinyPets TinyPets is a retro pixel-art web game created as a group project. Players can make an account, earn credits, buy randomized eggs from the in-game shop, hatch them through a click-based hatching sequence, and collect the pets they receive. Each pet is saved to the player’s collection with its own unique ID and sell value, giving players the option to sell pets for credits and continue buying and hatching more eggs. My main contribution was the backend of the website. I worked on the server-side logic, database interactions, and API routes that supported the shop, egg purchasing, hatching system, and pet collection features.",
    "images": [
      "projects/TinyPets/hatched.png",
      "projects/TinyPets/hatching.png",
      "projects/TinyPets/login.png",
      "projects/TinyPets/main-menu.png",
      "projects/TinyPets/my-pets.png",
      "projects/TinyPets/store.png"
    ],
    "link": null
  },
  {
    "title": "xArm Checkers Integration",
    "description": "xArm Checkers Integration Built a system that lets a physical xArm robotic arm play checkers on a real board, driven by a web-based game. This project combines two earlier independent projects — the web-based Checkers Online game (built for a CS course) and the xArm vision-guided pick-and-place system (built across RBE 3001 robotics labs) — into a single end-to-end pipeline. When a player makes a move in the web game, it writes the move to a queue file (queue.jsonl). A MATLAB bridge script (run_board_bridge.m) watches that file and wakes up the moment a new move arrives. Using a calibration step with an overhead camera, the system knows the exact real-world millimeter coordinates of every board square (A1–H8) relative to the robot. The arm then executes the move: it hovers over the source square, descends, grabs the piece with the gripper, lifts back up, travels to the destination square, and places the piece down. The motion relies on inverse kinematics and joint-angle planning developed in the earlier robotics labs. After each move, the camera takes a snapshot of the physical board and sends it back to the web server so the digital game state stays in sync with the real board.",
    "images": [],
    "link": null
  },
  {
    "title": "xArm Color Ball Sorter",
    "description": "Vision-Guided Robotic Sorting System (RBE 3001) Built a vision-guided robotic sorting system over five robotics labs using an xArm robotic arm and an overhead camera. The system detects colored balls on a custom checkerboard workspace, identifies their color and position, then commands the robot to pick them up and place them into the correct color-coded bins. I designed the checkerboard, tile grid, ball holders, and camera mount in Fusion 360, then 3D printed the parts. The checkerboard also served as a calibration tool, allowing the camera to convert pixel locations into real-world coordinates that the robot could reach. The project progressed from basic arm control to forward kinematics, inverse kinematics, trajectory planning, singularity avoidance, and finally full camera-based pick-and-place automation. By the final stage, the system could sort red, orange, yellow, and green balls without manual input. After completing these labs I extended this work into a new project by combining it with the web-based Checkers Online game I built for a CS course. The robot arm's pick-and-place pipeline, camera calibration system, and IK solver from this project became the foundation of the xArm Checkers Integration, where the arm now physically plays checkers on a real board driven by moves from a live browser game.",
    "images": [
      "projects/xArm Color Ball Sorter/cad-assembled.png",
      "projects/xArm Color Ball Sorter/cad-exploded.png",
      "projects/xArm Color Ball Sorter/robot-gripper.png",
      "projects/xArm Color Ball Sorter/robot-overview.png",
      "projects/xArm Color Ball Sorter/robot-picking.png"
    ],
    "link": null
  }
];

var BG_IMAGES = [
  "projects/3D Printed Drone/cad-exploded.png",
  "projects/Checkers Online/gameplay.png",
  "projects/Checkers Online/login-screen.png",
  "projects/ROS2 SLAM Autonomous Explorer/01-robot-hardware.png",
  "projects/ROS2 SLAM Autonomous Explorer/02-robot-exploring.png",
  "projects/ROS2 SLAM Autonomous Explorer/03-rviz-map-building.png",
  "projects/ROS2 SLAM Autonomous Explorer/04-rviz-completed-map.png",
  "projects/TinyPets/hatched.png",
  "projects/TinyPets/hatching.png",
  "projects/TinyPets/login.png",
  "projects/TinyPets/main-menu.png",
  "projects/TinyPets/my-pets.png",
  "projects/TinyPets/store.png",
  "projects/xArm Color Ball Sorter/cad-assembled.png",
  "projects/xArm Color Ball Sorter/cad-exploded.png",
  "projects/xArm Color Ball Sorter/robot-gripper.png",
  "projects/xArm Color Ball Sorter/robot-overview.png",
  "projects/xArm Color Ball Sorter/robot-picking.png"
];
